name: openvibe_neurofeedback
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - pip
  - pip:
      - pygame==2.6.1
      - pylsl==1.18.1
      - pillow
      - pyparsing
      - cycler
      - kiwisolver
      - fonttools
      - contourpy
